---
embed_dim : 768
num_encoders : 12
hidden_dim : 3072
num_heads : 12
num_classes : 10
eps : 1e-8

Epochs : 2
batch_size : 512
beta1 : 0.9
beta2 : 0.999
weight_decay : 0.01
image_size : 384
base_lr : 0.01
scheduler_type: "linear"
